title: Adam's Space
author: Adam Berg
email: adam@xyzdigital.com
description: MySpace 2.0
show_excerpts: true
excerpt_separator: <!--more-->

permalink: /:categories/:title

theme: minima

twitter_username: devtails
github_username:  adamjberg

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

google_analytics: UA-176603487-1

rss: Subscribe