title: xyz digital
show_excerpts: true

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag

jekyll-archives:
  enabled:
    - categories
  layouts: 
    category: category-archive  

google_analytics: UA-168026795-1
